### ISSUE TITLE
Persisting changes made in python script

### ISSUE THREAD

**Issue by meinnamehier** [OzymandiasTheGreat/python-libinput#16]
Hi, 
I am sorry if I am posting an inappropriate newbie question, but I do not know how to proceed.
I am using a touchscreen tft device (QDtech MPI5001, http://www.lcdwiki.com/5inch_HDMI_Display-B), powered by a Raspberry Pi 3B running LibreElec.
I want to rotate the screen by 180°. I can rotate the display easily, but the touch input is then not rotated.
I stumbled upon python.libinput and gave it a try.
I have the following script already running:
(the first part is specific to LibreElec and it's limitations)
```
import sys
sys.path.append('/storage/python_libinput/')
sys.path.append('/opt/lib/python2.7/site-packages')

from libinput import LibInput, ContextType
li = LibInput(context_type=ContextType.PATH)
screen = li.add_device('/dev/input/event0')
print(screen.name)
print('Has Matrix:', screen.config.calibration.has_matrix())
print('Default matrix:',screen.config.calibration.default_matrix)
print('Old matrix:', screen.config.calibration.matrix)
screen.config.calibration.set_matrix([-1,0,1,0,-1,1])
print('New matrix:', screen.config.calibration.matrix)
```
The output is:
```
QDtech MPI5001
('Has Matrix:', True)
('Default matrix:', (False, (1.0, 0.0, 0.0, 0.0, 1.0, 0.0)))
('Old matrix:', (False, (1.0, 0.0, 0.0, 0.0, 1.0, 0.0)))
ConfigStatus.SUCCESS
('New matrix:', (True, (-1.0, 0.0, 1.0, 0.0, -1.0, 1.0)))
```
When I rerun the script, the output is the same.
Also the touch input is not rotated on the display. 
How do I make the changes persist? It would be great if you could help me.
My end goal is to have the script running at startup and rotating the touch input for as long as the Pi is running.
Thanks in advance!

**Comment by meinnamehier** [comment]
Nevermind, I went the worng track here. 
A solution for my problem: https://forum.libreelec.tv/thread/22089-rotating-tft-touchscreen-mpi5001/#post140488

**Comment by whot** [comment]
fwiw, think of libinput like running `grep` on a file (the device events). you can start a new `grep` on the same file but it won't change the behaviour of the `grep` instance the compositor uses to gather events. That's your problem there - you need to change the calibration in the compositor's instance and the only way to do this is either udev or to tell the compositor to set the calibration.

**Comment by meinnamehier** [comment]
Thanks for your explanation, it really helps in understanding (i had some inkling it worked like that)
