### ISSUE TITLE
python-libinput on PyPI not updated.

### ISSUE THREAD

**Issue by Py-GNU-Unix** [OzymandiasTheGreat/python-libinput#18]
python-libinput 2.0 has been released, but on [PyPI](https://pypi.org/project/python-libinput/), it hasn't been updated since version 1.0. Can you update it? 

PS: good job. That's a very good library.

**Comment by somini** [comment]
Duplicate of #13

**Comment by somini** [comment]
Just a heads up, this was closed because the project is looking for maintainers, not because it's fixed.
