### ISSUE TITLE
Mouse button enum does not match up with physical buttons

### ISSUE THREAD

**Issue by minus7** [OzymandiasTheGreat/python-libinput#6]
E.g. pressing the forward button on my mouse makes `get_button()` return `BTN_EXTRA`.

**Comment by OzymandiasTheGreat** [comment]
I'm doing away with Key/Button enumerations, see #5 .
Altho this is NOT a bug. This maybe unintuitive, but this button is mapped as `BTN_EXTRA` in the kernel and mapping it to forward function is done on a higher level.
Unless `python-evdev` maps it to `BTN_FORWARD` which would mean that there's something very wrong with the current implementation of `python-libinput`.

**Comment by whot** [comment]
nah, it's a common issue and just a confusion in how the kernel defines the button names. Most mice just number the buttons sequentially. Works for LMR but buttons 4 and 5 are mapped to `BTN_SIDE` and `BTN_EXTRA`. In X, they're mapped to logical buttons 8 and 9 (buttons 4-7 are reserved for scrolling) and logical button 8/9 are *interpreted* as back/forward by many applications. This issue can be closed, there's nothing to fix here, it's just a confusing part of life.

**Comment by minus7** [comment]
So for X11 xf86-input-libinput does the re-mapping then, I guess. They do make relatively little sense in this then, and removing is reasonable.

**Comment by whot** [comment]
note that a lot of what X does is for historical reasons. Like the buttons 4-7 being reserved is because X pre-dates mice with scroll-wheels and they had to be retro-fitted.
